version: '3.8'
services:
  app:
    container_name: envia-guides-ms
    restart: always
    build: .
    env_file: .env
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - KAFKAHOST=${KAFKAHOST}
      - KAFKAUSER=${KAFKAUSER}
      - KAFKAKEY=${KAFKAKEY}
