version: '3.8'
services:
  envia-ms:
    container_name: envia-ms
    image: node:latest
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FOLDER_PLANILLAS=${FOLDER_PLANILLAS}
      - POSTGRES_HOST_AUTH_METHOD=trust
