import { GuideViewEntity, status_guides } from '../entities';

export const MockPDFGuide: GuideViewEntity = {
  id_guide: '0a49b63c-c9bd-4403-8f5a-4e87b160df7f',
  status_guide: status_guides.CREATED,
  date_admission: new Date(),
  notes_guide: 'Pago en sucursal',
  observations_guide: 'se daño la paqueteria',
  content_guide: 'Pantalla de computo',
  units_in_guide: 1,
  weight_in_guide: 5,
  volume_in_guide: 0,
  weight_payment_guide: 0,
  declared_value_guide: 200000,
  service_value_guide: 0,
  freight_guide: 0,
  other_cost_guide: 0,
  origin_city: 'Bogotá',
  origin_regional: 'Bogotá',
  destination_city: 'Medellin',
  destination_regional: 'Medellin',
  address_addressee_in_guide: 'calle falsa #123',
  document_sender: '125987463',
  first_name_sender: 'Juan',
  last_name_sender: 'Pérez',
  phone_sender: '3215748526',
  address_sender: '',
  postal_code_sender: 255874,
  first_name_addressee: 'David',
  last_name_addressee: 'Pardo',
  address_addressee: 'Calle falsa 123',
  phone_addressee: '3214447896',
  document_addressee: '8854713',
  postal_code_addressee: 998566,
  assigned_route: ''
};
