export const MockPlanilla = {
  id_solicitud: '1',
  empresa_recoleccion: 'alkosto',
  titulo_planilla: 'Planilla de recolección',
  fecha_creacion: '20/09/2021',
  programa_planilla: 'Alfresco',
  usuario_planilla: 'David Ramírez',
  fecha_planilla: '21/09/2021',
  nombre_planilla: 'Ruta Alkosto',
  conductor_planilla: 'Pepito Pérez',
  operador1_planilla: 'Juanito Sanchez',
  operador2_planilla: '',
  pagina_planilla: '1',
  tipo_planilla: 'Ruta Nacional',
  paquetes: [
    {
      id_guia: '1',
      nombre_destinatario: 'ASDFGH',
      direccion_destinatario: 'ASDRGFH',
      telefono_destinatario: '4552154',
      peso_guia: '14',
      clasificacion_guia: 'caja',
      contenido_guia: 'DFGHNM',
      destino_guia: 'Filadelfia',
      estado_guia: 'recoleccion',
      documento_relacionado: '',
      id_solicitud: '',
      documento_destinatario: '',
      fecha_admision: '',
      fecha_entrega: '',
      valor_declarado: 1200000,
      valor_servicio: 0,
    },
    {
      id_guia: '2',
      nombre_destinatario: 'ASDFGH',
      direccion_destinatario: 'ASDRGFH',
      telefono_destinatario: '4552154',
      peso_guia: '14',
      clasificacion_guia: 'caja',
      contenido_guia: 'DFGHNM',
      destino_guia: 'Filadelfia',
      estado_guia: 'recoleccion',
      documento_relacionado: '',
      id_solicitud: '',
      documento_destinatario: '',
      fecha_admision: '',
      fecha_entrega: '',
      valor_declarado: 1200000,
      valor_servicio: 0,
    },
    {
      id_guia: '3',
      nombre_destinatario: 'ASDFGH',
      direccion_destinatario: 'ASDRGFH',
      telefono_destinatario: '4552154',
      peso_guia: '14',
      clasificacion_guia: 'caja',
      contenido_guia: 'DFGHNM',
      destino_guia: 'Filadelfia',
      estado_guia: 'recoleccion',
      documento_relacionado: '',
      id_solicitud: '',
      documento_destinatario: '',
      fecha_admision: '',
      fecha_entrega: '',
      valor_declarado: 1200000,
      valor_servicio: 0,
    },
    {
      id_guia: '4',
      nombre_destinatario: 'ASDFGH',
      direccion_destinatario: 'ASDRGFH',
      telefono_destinatario: '4552154',
      peso_guia: '14',
      clasificacion_guia: 'caja',
      contenido_guia: 'DFGHNM',
      destino_guia: 'Filadelfia',
      estado_guia: 'recoleccion',
      documento_relacionado: '',
      id_solicitud: '',
      documento_destinatario: '',
      fecha_admision: '',
      fecha_entrega: '',
      valor_declarado: 1200000,
      valor_servicio: 0,
    },
    {
      id_guia: '5',
      nombre_destinatario: 'ASDFGH',
      direccion_destinatario: 'ASDRGFH',
      telefono_destinatario: '4552154',
      peso_guia: '14',
      clasificacion_guia: 'caja',
      contenido_guia: 'DFGHNM',
      destino_guia: 'Filadelfia',
      estado_guia: 'recoleccion',
      documento_relacionado: '',
      id_solicitud: '',
      documento_destinatario: '',
      fecha_admision: '',
      fecha_entrega: '',
      valor_declarado: 1200000,
      valor_servicio: 0,
    },
  ],
};
